function w = waveformPCA(w)
% Assumes multitaper spectra has already been run

% Will manually select stations/times for the moment

ichans = {...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}, ...
    {}};